### ISSUE TITLE
EEMD triggers large number of tkinter open windows?

### ISSUE THREAD

**Issue by MortimerMcMire** [laszukdawid/PyEMD#78] opened 2020-04-17 17:56 UTC
Specifically line 191 of EEMD 
`max_imfNo = max([IMFs.shape[0] for IMFs in all_IMFs_1])`

whenever it hits this line it opens up a tkinter "open" file dialogue window for every IMF generated

I know in other programs sometimes they ask for user input to generate noise but I don't think its the case here?

edit: for the record, the result looks fine, and regular EMD does not have this behavior when I run the exact same input into it.

**Comment by laszukdawid** [comment] 2020-04-17 22:54
That is... surprising. When did you download the module? What does it say when you do `print(PyEMD.__version__)`?

I'm guessing that was about a month ago. That line used to be the first line when the EEMD would be computed, due to lazy evaluation a few lines earlier with `imap`. My suspicion is that either your IDE uses the same way of handling processes and gets confused, or that the lib for handling processes is using tkinter behind the scene.

What OS are you using?

**Comment by MortimerMcMire** [comment] 2020-04-20 20:04
Version doesn't exist as an attribute in my PyEMD. Installed it from PyPi on 2020-04-07, using IDLE on W10

**Comment by laszukdawid** [comment] 2024-03-01 05:33
Closing as it's been a while. I don't think the issue is there anymore.

**Closed by laszukdawid** 2024-03-01 05:33 UTC
