### ISSUE TITLE
The result of eemd decomposition

### ISSUE THREAD

**Issue by wang1xu** [laszukdawid/PyEMD#92] opened 2021-05-17 03:29 UTC
Hello, I would like to ask about this eemd decomposition. The result of eemd decomposition is different each time. If I want to get the same imf component result, what parameters should be set?

**Comment by laszukdawid** [comment] 2021-06-04 16:55
Hi @wang1xu,

The result of EEMD is different each time by design. Or, rather it is the expected consequence of the design.

Every time you do EEMD you do multiple EMD on a signal with noise and that noise is noise so it is going to be different.

To make the decomposition reproducible one needs to set a seed for the random number generator. In case of EEMD you need to pass any integer to `noise_seed` method ([doc](https://pyemd.readthedocs.io/en/latest/eemd.html#PyEMD.EEMD.noise_seed)).

A short snippet
```python
from PyEMD import EEMD

seed = 32167  # Any number is fine. Decomposition should be the same for the same number.
eemd = EEMD()
eemd.noise_seed(seed)
```

**Comment by laszukdawid** [comment] 2021-07-27 18:52
Closing issue as there wasn't any reply for a while.

**Closed by laszukdawid** 2021-07-27 18:52 UTC
