### ISSUE TITLE
Problem with EEMD code

### ISSUE THREAD

**Issue by cscp230198** [laszukdawid/PyEMD#72] opened 2020-02-17 16:48 UTC
Hello, we´re trying to use your EEMd code for an EEG signal analysis, however when we try to run our code all of the eIMFs are flat lines. Our signal is called ST2 and has its own linspace (t) defined at the very beginning of our code. Hope you can help us. Thank you!
![image](https://user-images.githubusercontent.com/61157875/74672422-db902500-5172-11ea-9bf0-6fb2a46fefe3.png)

**Comment by laszukdawid** [comment] 2020-02-18 00:52
Hey,

I'm not sure why this isn't working. Seems fine. My initial guesses are that it's either a problem with converting your data format or the scale on displayed eIMFs is too high, thus it looks like a flat line. 

Let me recommend to start with minimal working example and then add complexity until it breaks. Also, since you're working with Jupyter, it's easier to restart the kernel to make sure that you're not reusing some old variables.

Code below was tested and should work. Let me know if you have any problems.

[1] Basic example
```python
import numpy as np
import pylab as plt
from PyEMD import EEMD

t = np.linspace(0, 1, 100)
s = np.random.normal(size=100)

eemd = EEMD(trails=5)
eIMFs = eemd(s, t)
n_imfs, sample_size = eIMFs.shape

fig, axes = plt.subplots(n_imfs, 1, figsize=(2*n_imfs, 8))
for n, imf in enumerate(eIMFs):
    ax = axes[n]
    ax.plot(t, imf)

plt.show()
```

**Comment by cscp230198** [comment] 2020-02-18 01:56
Hi, thanks for answering so quickly , I tried running the basic example you sent us , however we still got flat lines. Is it possible something is wrong with my computer? I made sure I restarted the kernel, several times . I am using Windows 10 64-bits . Thank you 
 
![image](https://user-images.githubusercontent.com/61157875/74697179-7d3d6380-51bf-11ea-86e3-0e952f605c0d.png)

**Comment by cscp230198** [comment] 2020-02-18 02:00
Hi, thanks for answering so quickly , I tried running the basic example you sent us , however we still got flat lines. Is it possible something is wrong with my computer? I made sure I restarted the kernel, several times . I am using Windows 10 64-bits . Thank you
![image](https://user-images.githubusercontent.com/61157875/74697396-3308b200-51c0-11ea-9f4a-fa9a62c7756f.png)

**Comment by laszukdawid** [comment] 2020-02-18 02:04
It's unlikely computer's fault; more likely implementation or environment settings.

How and when did you install the PyEMD?

Could you please send me or attqch to the thread the sample data that doesn't work?

**Comment by cscp230198** [comment] 2020-02-18 02:11
I send you my notebook and the Excel file with all the data. The last cell on our python notebook is where we tried implementing your EEMD code but didn´t work. Thank you 

http://localhost:8888/edit/Miniconda3/Sistemas%20inteligentes/EPILEPSY/SeizuresP1.xlsx
http://localhost:8888/notebooks/Miniconda3/Sistemas%20inteligentes/EPILEPSY/EPILEPSY_%20EEMD.ipynb

**Comment by cscp230198** [comment] 2020-02-18 02:14
This is the link I used for installing the PyEMD. 
https://pyemd.readthedocs.io/en/latest/intro.html
I should mention I have tried your EMD example and it worked perfectly so I´m not sure it is something about my PyEMD installation. 
![image](https://user-images.githubusercontent.com/61157875/74698022-11a8c580-51c2-11ea-918b-b19692291507.png)

**Comment by laszukdawid** [comment] 2020-02-22 17:23
Hey @cscp230198,
Apologies for the delay. I just checked your code and it looks fine. The problem is the same as reported by another user (https://github.com/laszukdawid/PyEMD/issues/65) and it has been resolved in the last two weeks.

To resolve the issue please delete current version (`pip uninstall EMD-signal`), restart the jupyter environment and install the newest version (`pip install EMD-signal`).

Hope this helps. Please let me know of the progress.

**Comment by laszukdawid** [comment] 2020-03-10 18:02
Hey @cscp230198 , I'm closing this ticket since there wasn't any communication in the past 17 days. Feel free to reopen if you are still having problems.

**Closed by laszukdawid** 2020-03-10 18:02 UTC
