### ISSUE TITLE
EEMD Ensemble dependency

### ISSUE THREAD

**Issue by kimyoungjin06** [laszukdawid/PyEMD#85] opened 2021-01-12 08:05 UTC
Happy new year @laszukdawid  ;)
I am always thankful to you and your package!
I have some question about **EEMD**

### Problem: Ensemble dependency

In my study, I check ensemble dependency of EEMD using on the tidal data.

nearby over 100 trials, there is some strange point about a scale of the latter modes.

I think these modes (except the last mode) must have zero-means with specific amplitude.
But, in the case with higher # of ensemble, some latter mode does not have zero-means.

### Question

Is it the problem about the mathematical algorithm or computational part?

#### Data
<details>
  <summary>
    2 cols, 699 rows
  </summary>

```
	t	s
1	1960.4583	7080
2	1960.5417	7069
3	1960.625	7200
4	1960.7083	7098
5	1960.7917	7097
6	1960.875	7051
7	1960.9583	6959
8	1961.0417	6978
9	1961.125	6999
10	1961.2083	6994
11	1961.2917	7031
12	1961.375	7094
13	1961.4583	7155
14	1961.5417	7125
15	1961.625	7150
16	1961.7083	7108
17	1961.7917	7072
18	1961.875	6998
19	1961.9583	6949
20	1962.0417	6945
21	1962.125	6856
22	1962.2083	6850
23	1962.2917	6875
24	1962.375	6937
25	1962.4583	7048
26	1962.5417	7090
27	1962.625	7090
28	1962.7083	7107
29	1962.7917	7042
30	1962.875	7019
31	1962.9583	6968
32	1963.0417	6933
33	1963.125	6874
34	1963.2083	6927
35	1963.2917	6903
36	1963.375	6960
37	1963.4583	7076
38	1963.5417	7058
39	1963.625	7122
40	1963.7083	7093
41	1963.7917	6986
42	1963.875	6957
43	1963.9583	6916
44	1964.0417	6944
45	1964.125	6883
46	1964.2083	6886
47	1964.2917	6900
48	1964.375	7032
49	1964.4583	7062
50	1964.5417	7033
51	1964.625	7140
52	1964.7083	7171
53	1964.7917	7046
54	1964.875	7000
55	1964.9583	6969
56	1965.0417	6949
57	1965.125	6904
58	1965.2083	6947
59	1965.2917	6868
60	1965.375	6955
61	1965.4583	7052
62	1965.5417	7057
63	1965.625	7036
64	1965.7083	7068
65	1965.7917	6975
66	1965.875	7006
67	1965.9583	6911
68	1966.0417	6841
69	1966.125	6854
70	1966.2083	6949
71	1966.2917	6987
72	1966.375	6976
73	1966.4583	6976
74	1966.5417	6998
75	1966.625	7177
76	1966.7083	7130
77	1966.7917	7016
78	1966.875	6811
79	1966.9583	6896
80	1967.0417	6838
81	1967.125	6835
82	1967.2083	6842
83	1967.2917	6872
84	1967.375	6974
85	1967.4583	7077
86	1967.5417	7117
87	1967.625	7074
88	1967.7083	7206
89	1967.7917	7108
90	1967.875	7003
91	1967.9583	6951
92	1968.0417	6881
93	1968.125	6802
94	1968.2083	6812
95	1968.2917	6853
96	1968.375	6945
97	1968.4583	6963
98	1968.5417	7058
99	1968.625	7115
100	1968.7083	7109
101	1968.7917	7025
102	1968.875	6918
103	1968.9583	6964
104	1969.0417	6937
105	1969.125	6871
106	1969.2083	6886
107	1969.2917	6922
108	1969.375	7047
109	1969.4583	7092
110	1969.5417	7076
111	1969.625	7040
112	1969.7083	7053
113	1969.7917	7024
114	1969.875	6929
115	1969.9583	6862
116	1970.0417	6886
117	1970.125	6913
118	1970.2083	6877
119	1970.2917	6864
120	1970.375	6968
121	1970.4583	7023
122	1970.5417	7060
123	1970.625	7082
124	1970.7083	7092
125	1970.7917	7030
126	1970.875	6967
127	1970.9583	6909
128	1971.0417	6924
129	1971.125	6885
130	1971.2083	6850
131	1971.2917	6864
132	1971.375	6969
133	1971.4583	7033
134	1971.5417	7052
135	1971.625	7132
136	1971.7083	7197
137	1971.7917	7015
138	1971.875	6902
139	1971.9583	6791
140	1972.0417	6916
141	1972.125	6946
142	1972.2083	6917
143	1972.2917	6896
144	1972.375	6976
145	1972.4583	7027
146	1972.5417	7125
147	1972.625	7077
148	1972.7083	7117
149	1972.7917	6991
150	1973.0417	6921
151	1973.125	6945
152	1973.2083	6930
153	1973.2917	6972
154	1973.375	6992
155	1973.4583	7055
156	1973.5417	7100
157	1973.625	7085
158	1973.7083	7093
159	1973.7917	7052
160	1973.875	6972
161	1973.9583	6911
162	1974.0417	7005
163	1974.125	6963
164	1974.2083	6885
165	1974.2917	6944
166	1974.375	7025
167	1974.4583	7110
168	1974.5417	7147
169	1974.625	7144
170	1974.7083	7092
171	1974.7917	7007
172	1974.875	6928
173	1974.9583	6965
174	1975.0417	6963
175	1975.125	6935
176	1975.2083	6927
177	1975.2917	6954
178	1975.375	7012
179	1975.4583	7109
180	1975.5417	7089
181	1975.625	7202
182	1975.7083	7198
183	1975.7917	7112
184	1975.875	7083
185	1975.9583	6987
186	1976.0417	6920
187	1976.125	6974
188	1976.2083	6920
189	1976.2917	6980
190	1976.375	7027
191	1976.4583	7121
192	1976.5417	7164
193	1976.625	7073
194	1976.7083	7205
195	1976.7917	7084
196	1976.875	6981
197	1976.9583	6964
198	1977.0417	6907
199	1977.125	6890
200	1977.2083	6863
201	1977.2917	6915
202	1977.375	6968
203	1977.4583	7107
204	1977.5417	7080
205	1977.625	7172
206	1977.7083	7147
207	1977.7917	7054
208	1977.875	6980
209	1977.9583	6985
210	1978.0417	6943
211	1978.125	6929
212	1978.2083	6954
213	1978.2917	6960
214	1978.375	6984
215	1978.4583	7044
216	1978.5417	7085
217	1978.625	7105
218	1978.7083	7089
219	1978.7917	7056
220	1978.875	6964
221	1978.9583	6915
222	1979.0417	6868
223	1979.125	6916
224	1979.2083	6956
225	1979.2917	6944
226	1979.375	7032
227	1979.4583	7066
228	1979.5417	7135
229	1979.625	7088
230	1979.7083	7107
231	1979.7917	7095
232	1979.875	6930
233	1979.9583	6913
234	1980.0417	6932
235	1980.125	6794
236	1980.2083	6856
237	1980.2917	6880
238	1980.375	6953
239	1980.4583	6976
240	1980.5417	7058
241	1980.625	7140
242	1980.7083	7108
243	1980.7917	7018
244	1980.875	6943
245	1980.9583	6975
246	1981.0417	6912
247	1981.125	6913
248	1981.2083	6891
249	1981.2917	6935
250	1981.375	6946
251	1981.4583	7030
252	1981.5417	7032
253	1981.625	7102
254	1981.7083	7108
255	1981.7917	7025
256	1981.875	6952
257	1981.9583	6911
258	1982.0417	6878
259	1982.125	6868
260	1982.2083	6880
261	1982.2917	6953
262	1982.375	6999
263	1982.4583	7032
264	1982.5417	7056
265	1982.625	7109
266	1982.7083	7115
267	1982.7917	7038
268	1982.875	6923
269	1982.9583	6870
270	1983.0417	6866
271	1983.125	6889
272	1983.2083	6942
273	1983.2917	6945
274	1983.375	6989
275	1983.4583	7100
276	1983.5417	7103
277	1983.625	7134
278	1983.7083	7173
279	1983.7917	7033
280	1983.875	6935
281	1983.9583	6920
282	1984.0417	6915
283	1984.125	6892
284	1984.2083	6890
285	1984.2917	6926
286	1984.375	6996
287	1984.4583	7084
288	1984.5417	7100
289	1984.625	7108
290	1984.7083	7063
291	1984.7917	7057
292	1984.875	7003
293	1984.9583	6959
294	1985.0417	6889
295	1985.125	6938
296	1985.2083	6870
297	1985.2917	6931
298	1985.375	6999
299	1985.4583	7112
300	1985.5417	7139
301	1985.625	7114
302	1985.7083	7070
303	1985.7917	7067
304	1985.875	7016
305	1985.9583	6904
306	1986.0417	6887
307	1986.125	6906
308	1986.2083	6980
309	1986.2917	6964
310	1986.375	6987
311	1986.4583	7065
312	1986.5417	7118
313	1986.625	7163
314	1986.7083	7132
315	1986.7917	7059
316	1986.875	6948
317	1986.9583	7038
318	1987.0417	6987
319	1987.125	6951
320	1987.2083	6948
321	1987.2917	6942
322	1987.375	6992
323	1987.4583	7068
324	1987.5417	7107
325	1987.625	7131
326	1987.7083	7131
327	1987.7917	7048
328	1987.875	6994
329	1987.9583	6985
330	1988.0417	6908
331	1988.125	6900
332	1988.2083	6950
333	1988.2917	6975
334	1988.375	7029
335	1988.4583	7110
336	1988.5417	7159
337	1988.625	7151
338	1988.7083	7165
339	1988.7917	7111
340	1988.875	6985
341	1988.9583	6920
342	1989.0417	6946
343	1989.125	6910
344	1989.2083	6961
345	1989.2917	6989
346	1989.375	7034
347	1989.4583	7091
348	1989.5417	7123
349	1989.625	7245
350	1989.7083	7181
351	1989.7917	7034
352	1989.875	7038
353	1989.9583	7032
354	1990.0417	6958
355	1990.125	6902
356	1990.2083	6939
357	1990.2917	7026
358	1990.375	7001
359	1990.4583	7079
360	1990.5417	7128
361	1990.625	7165
362	1990.7083	7159
363	1990.7917	7047
364	1990.875	6987
365	1990.9583	6896
366	1991.0417	6955
367	1991.2083	6934
368	1991.2917	6967
369	1991.375	7012
370	1991.4583	7090
371	1991.5417	7135
372	1991.625	7284
373	1991.7083	7192
374	1991.7917	7137
375	1991.875	6991
376	1991.9583	7005
377	1992.0417	6966
378	1992.125	6946
379	1992.2083	6982
380	1992.2917	7064
381	1992.375	7078
382	1992.5417	7089
383	1992.625	7177
384	1992.7083	7184
385	1992.7917	7161
386	1992.875	7035
387	1992.9583	6970
388	1993.0417	6962
389	1993.125	6924
390	1993.2083	6967
391	1993.2917	7044
392	1993.375	7044
393	1993.4583	7069
394	1993.5417	7142
395	1993.625	7177
396	1993.7083	7123
397	1993.7917	7065
398	1993.875	6962
399	1993.9583	6913
400	1994.0417	6999
401	1994.125	6970
402	1994.2083	6943
403	1994.2917	7018
404	1994.375	7022
405	1994.4583	7085
406	1994.5417	7107
407	1994.625	7142
408	1994.7083	7185
409	1994.7917	7103
410	1994.875	6972
411	1994.9583	6959
412	1995.0417	6962
413	1995.125	7018
414	1995.2083	6976
415	1995.2917	6998
416	1995.375	7044
417	1995.4583	7103
418	1995.5417	7056
419	1995.625	7028
420	1995.7083	7076
421	1995.7917	7045
422	1995.875	6937
423	1995.9583	7016
424	1996.0417	6962
425	1996.125	6895
426	1996.2083	6915
427	1996.2917	6939
428	1996.375	7045
429	1996.4583	7092
430	1996.5417	7098
431	1996.625	7147
432	1996.7083	7121
433	1996.7917	7080
434	1996.875	7008
435	1996.9583	6957
436	1997.0417	6979
437	1997.125	6968
438	1997.2083	6942
439	1997.2917	6963
440	1997.375	7048
441	1997.4583	7136
442	1997.5417	7152
443	1997.625	7160
444	1997.7083	7152
445	1997.7917	7001
446	1997.875	7027
447	1997.9583	7013
448	1998.0417	6995
449	1998.125	6987
450	1998.2083	7002
451	1998.2917	6990
452	1998.375	7036
453	1998.4583	7186
454	1998.5417	7225
455	1998.625	7180
456	1998.7083	7206
457	1998.7917	7137
458	1998.875	7031
459	1998.9583	6978
460	1999.0417	6970
461	1999.125	6920
462	1999.2083	7020
463	1999.2917	7050
464	1999.375	7040
465	1999.4583	7100
466	1999.5417	7170
467	1999.625	7220
468	1999.7083	7210
469	1999.7917	7180
470	1999.875	7100
471	1999.9583	6980
472	2000.0417	7000
473	2000.125	6990
474	2000.2083	7010
475	2000.2917	7000
476	2000.375	7050
477	2000.4583	7080
478	2000.5417	7120
479	2000.625	7140
480	2000.7083	7230
481	2000.7917	7050
482	2000.875	7010
483	2000.9583	7000
484	2001.0417	7040
485	2001.125	6940
486	2001.2083	7000
487	2001.2917	6980
488	2001.375	7040
489	2001.4583	7100
490	2001.5417	7090
491	2001.625	7190
492	2001.7083	7230
493	2001.7917	7160
494	2001.875	7000
495	2001.9583	6950
496	2002.0417	6970
497	2002.125	6940
498	2002.2083	6930
499	2002.2917	6990
500	2002.375	7090
501	2002.4583	7130
502	2002.5417	7220
503	2002.625	7210
504	2002.7083	7220
505	2002.7917	7100
506	2002.875	7020
507	2002.9583	7020
508	2003.0417	6970
509	2003.125	7000
510	2003.2083	6980
511	2003.2917	6980
512	2003.375	7070
513	2003.4583	7150
514	2003.5417	7130
515	2003.625	7170
516	2003.7083	7170
517	2003.7917	7140
518	2003.875	7080
519	2003.9583	6980
520	2004.0417	6980
521	2004.125	6930
522	2004.2083	6940
523	2004.2917	7000
524	2004.375	7090
525	2004.4583	7090
526	2004.5417	7170
527	2004.625	7260
528	2004.7083	7190
529	2004.7917	7100
530	2004.875	7000
531	2004.9583	7020
532	2005.0417	6999
533	2005.125	6985
534	2005.2083	6928
535	2005.2917	6974
536	2005.375	7048
537	2005.4583	7093
538	2005.5417	7112
539	2005.625	7161
540	2005.7083	7165
541	2005.7917	7051
542	2005.875	7058
543	2005.9583	7005
544	2006.0417	7021
545	2006.125	6940
546	2006.2083	6951
547	2006.2917	7054
548	2006.375	7061
549	2006.4583	7121
550	2006.5417	7146
551	2006.625	7195
552	2006.7083	7185
553	2006.7917	7139
554	2006.875	7040
555	2006.9583	7002
556	2007.0417	6974
557	2007.125	6940
558	2007.2083	7046
559	2007.2917	7025
560	2007.375	7092
561	2007.4583	7077
562	2007.5417	7158
563	2007.625	7159
564	2007.7083	7235
565	2007.7917	7049
566	2007.875	7038
567	2007.9583	7040
568	2008.0417	6990
569	2008.125	6945
570	2008.2083	6987
571	2008.2917	7037
572	2008.375	7108
573	2008.4583	7149
574	2008.5417	7133
575	2008.625	7189
576	2008.7083	7129
577	2008.7917	7081
578	2008.875	7021
579	2008.9583	6989
580	2009.0417	6974
581	2009.125	7016
582	2009.2083	6964
583	2009.2917	7025
584	2009.375	7066
585	2009.4583	7137
586	2009.5417	7161
587	2009.625	7217
588	2009.7083	7234
589	2009.7917	7099
590	2009.875	7063
591	2009.9583	7138
592	2010.0417	7022
593	2010.125	7064
594	2010.2083	7017
595	2010.2917	7055
596	2010.375	7121
597	2010.4583	7110
598	2010.5417	7189
599	2010.625	7157
600	2010.7083	7184
601	2010.7917	7149
602	2010.875	7121
603	2010.9583	7083
604	2011.0417	7029
605	2011.125	7034
606	2011.2083	6980
607	2011.2917	7030
608	2011.375	7094
609	2011.4583	7132
610	2011.5417	7167
611	2011.625	7194
612	2011.7083	7266
613	2011.7917	7121
614	2011.875	7080
615	2011.9583	7034
616	2012.0417	7041
617	2012.125	6987
618	2012.2083	7031
619	2012.2917	6991
620	2012.375	7076
621	2012.4583	7159
622	2012.5417	7208
623	2012.625	7265
624	2012.7083	7238
625	2012.7917	7184
626	2012.875	7116
627	2012.9583	6994
628	2013.0417	6965
629	2013.125	6944
630	2013.2083	6981
631	2013.2917	7050
632	2013.375	7117
633	2013.4583	7128
634	2013.5417	7112
635	2013.625	7137
636	2013.7083	7116
637	2013.7917	7160
638	2013.875	7010
639	2013.9583	6991
640	2014.0417	6950
641	2014.125	7013
642	2014.2083	7037
643	2014.2917	7065
644	2014.375	7111
645	2014.4583	7179
646	2014.5417	7139
647	2014.625	7233
648	2014.7083	7205
649	2014.7917	7212
650	2014.875	7069
651	2014.9583	7015
652	2015.0417	7031
653	2015.125	7003
654	2015.2083	6964
655	2015.2917	7012
656	2015.375	7091
657	2015.4583	7132
658	2015.5417	7182
659	2015.625	7258
660	2015.7083	7242
661	2015.7917	7103
662	2015.875	7128
663	2015.9583	7071
664	2016.0417	7045
665	2016.125	6979
666	2016.2083	7028
667	2016.2917	7122
668	2016.375	7112
669	2016.4583	7169
670	2016.5417	7155
671	2016.625	7243
672	2016.7083	7322
673	2016.7917	7181
674	2016.875	7153
675	2016.9583	7088
676	2017.0417	7055
677	2017.125	7054
678	2017.2083	7065
679	2017.2917	7078
680	2017.375	7045
681	2017.4583	7155
682	2017.5417	7183
683	2017.625	7249
684	2017.7083	7220
685	2017.7917	7171
686	2017.875	7028
687	2017.9583	6956
688	2018.0417	6992
689	2018.125	6943
690	2018.2083	6955
691	2018.2917	7003
692	2018.375	7113
693	2018.4583	7129
694	2018.5417	7176
695	2018.625	7258
696	2018.7083	7197
697	2018.7917	7132
698	2018.875	7053
699	2018.9583	7079
```

</details>

#### Results

![image](https://user-images.githubusercontent.com/20521264/104285213-9dbc8d80-54f6-11eb-9034-152ad43539bc.png)

![image](https://user-images.githubusercontent.com/20521264/104285746-64385200-54f7-11eb-9799-9d08d3a8b84c.png)

![image](https://user-images.githubusercontent.com/20521264/104285770-6bf7f680-54f7-11eb-84dd-55ed1b9aa6a5.png)

**Comment by laszukdawid** [comment] 2021-01-17 03:01
Hey! Thanks for reaching out with this as it's an interesting question/observation :) (And great apologies for delay!)

My initial thought was that it's likely a computational bug but now I'm leaning towards the other explanation.

The assumption about IMF components being zero-centred, except for the last one, is true only for EMD. In case of EEMD, as an example, we are summing multiple components, and even though each can have a zero-mean the result might have offset, due to interference. In practise, however, the offset is "tiny", partially as a result of taking a mean over all IMFs for given order, which divides that small offset by ensemble size.

Regarding your particular question with your data, I believe that something expected but unwanted happened. Since the EEMD decomposes signal multiple times, each with a different noise, the number of produced IMFs will change. In your case I see that it returns between 4 and 7 IMFs + a trend. However, internally that trend is also considered as a proto-imf thus it's added to each proto-eimf. What you observed is likely those individual spurious trends being present in a few eIMFs.

I'm guessing, since you asked a question, and there are likely others who are wondering about it, that you'd like to be able to control for this effect. I don't it's doable right now... but it's an easy fix. Let me update that :)

**Comment by laszukdawid** [comment] 2021-01-17 19:42
I've just updated the EEMD code so that it supports handling trends separately (always as the last component). Check out EEMD's [class doc](https://pyemd.readthedocs.io/en/latest/eemd.html), but in short use `separate_trends` flag when initiating the class.

Example:
```
eemd = EEMD(separate_trends=True)
all_components = eemf(S)
eimfs, trend = all_components[:-1], trend[-1:]
```

With this, only the `trend` should have mean visibility different than 0. Hope this helps 👍

**Comment by kimyoungjin06** [comment] 2021-01-18 01:53
It's good!

It is a proper update. And I think the information about information about a number of IMFs - like a distribution. And, about variation of each IMF like this figure.
![image](https://user-images.githubusercontent.com/20521264/104863986-097d7b00-597b-11eb-9393-7bda4d2de281.png)
In above figure, the area is errorbar at each data.
But it is not necessary in PyEMD.

I can extract edit the module. 

Thanks, for your fast update!

**Comment by laszukdawid** [comment] 2021-01-18 18:11
Hi @kimyoungjin06, I'm sorry but I'm afraid I don't understand your reply :( Did my correction help? Do you see other problems? Not sure what that attached graph shows as well.

**Comment by kimyoungjin06** [comment] 2021-01-19 00:40
Original Problem is solved. My opinion is an additional suggestion. 

#### A measure of the variation or fluctuation 

- a number of IMFs on each IMF
- a values (or std) at the point in each IMF
- 
It can be used as an error bar.

**Comment by laszukdawid** [comment] 2021-01-23 17:50
I think I have an idea on how to add this, and potentially other stuff. Will likely work on within a week.

**Comment by laszukdawid** [comment] 2021-01-28 20:52
@kimyoungjin06 updated

**Comment by kimyoungjin06** [comment] 2021-02-03 08:33
I'm testing! 

I'll comment about update soon. 

Thanks a lot!

**Comment by pgupta18** [comment] 2021-02-26 10:37
![Figure_6](https://user-images.githubusercontent.com/79562882/109289170-d668ba00-784b-11eb-8580-c7fb5909685d.png)
Hello,
I am also facing the same problem that for 100 trials EEMD, the second last mode does not have zero- means. I tried the updated code with separate_trends=true. But still the problem is not rectified. The results with updated code is
![Figure_1](https://user-images.githubusercontent.com/79562882/109289661-876f5480-784c-11eb-9621-395b51e5da3a.png)

**Comment by laszukdawid** [comment] 2021-05-04 04:24
Hi @pgupta18,

Sorry for delay in response but unfortunately PyEMD has fallen low on my priority list. I'm trying to reply as soon as possible but often that is still a bit of delay.

You've provided interesting case. Could you write what PyEMD version you are using? Because EEMD allows any key arguments to be passed, there wouldn't be any feedback that you are using EEMD version that doesn't support `separate_trends`.

Since I don't have data to generate these curves you'd need to do a bit debugging on your side. Please check [individual imfs](https://github.com/laszukdawid/PyEMD/blob/master/PyEMD/EEMD.py#L250) generated through the EEMD and see whether there are any IMFs and not residue.

**Comment by laszukdawid** [comment] 2023-04-23 18:23
It's been 2 years since this problem was reported. I'm not sure if it has been resolved but I don't see any response to my latest comment; thus, I'm closing the ticket.

**Closed by laszukdawid** 2023-04-23 18:23 UTC
